#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 27, 2018 07:03:53 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

from system import manger_support


def vp_start_gui(user):
    # Starting point when module is the main routine.
    global var, w, root
    # this_user = user
    root = tk.Tk()
    manger_support.set_tk_var(user)
    top = Toplevel1(root)
    manger_support.init(root, top)
    root.mainloop()


var = None
w = None
w_win = None


def create_Toplevel1(root, *args, **kwargs):
    # tarting point when module is imported by another program.
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    manger_support.set_tk_var(manger_support.user)
    top = Toplevel1(w)
    manger_support.init(w, top)
    return w, top


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        # '''This class configures and populates the toplevel window.
        #    top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font10 = "-family {Microsoft YaHei UI} -size 12 -weight bold " \
                 "-slant roman -underline 0 -overstrike 0"
        font12 = "-family {Microsoft YaHei UI} -size 13 -weight bold " \
                 "-slant roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=[('selected', _compcolor), ('active', _ana2color)])

        top.geometry("397x399+616+131")
        top.title("管理员界面")
        top.configure(background="#d9d9d9")

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.firstframe = tk.Frame(top)
        self.firstframe.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.008)
        self.firstframe.configure(relief='groove')
        self.firstframe.configure(borderwidth="2")
        self.firstframe.configure(relief='groove')
        self.firstframe.configure(background="#d9d9d9")
        self.firstframe.configure(width=425)

        self.Label2 = tk.Label(self.firstframe)
        self.Label2.place(relx=0.1, rely=0.175, height=23, width=78)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''查找学生  ：''')

        self.Label3 = tk.Label(self.firstframe)
        self.Label3.place(relx=0.1, rely=0.275, height=23, width=77)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''查找教师  ：''')
        self.Label3.configure(width=77)

        self.Entry1 = tk.Entry(self.firstframe)
        self.Entry1.place(relx=0.375, rely=0.188, height=17, relwidth=0.36)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(textvariable=manger_support.student)

        self.Entry2 = tk.Entry(self.firstframe)
        self.Entry2.place(relx=0.375, rely=0.275, height=17, relwidth=0.36)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=manger_support.teacher)

        self.first_button_teacher = ttk.Button(self.firstframe)
        self.first_button_teacher.place(relx=0.775, rely=0.275, height=27, width=57)
        self.first_button_teacher.configure(command=manger_support.find_teacher)
        self.first_button_teacher.configure(takefocus="")
        self.first_button_teacher.configure(text='''查询''')
        self.first_button_teacher.configure(width=57)

        self.first_button_student = ttk.Button(self.firstframe)
        self.first_button_student.place(relx=0.775, rely=0.175, height=27, width=57)
        self.first_button_student.configure(command=manger_support.find_student)
        self.first_button_student.configure(takefocus="")
        self.first_button_student.configure(text='''查询''')

        self.Message1 = tk.Message(self.firstframe)
        self.Message1.place(relx=0.05, rely=0.6, relheight=0.263, relwidth=0.868)

        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(textvariable=manger_support.message1)
        self.Message1.configure(width=347)

        self.add_teacher_frame = tk.Frame(top)
        self.add_teacher_frame.place(relx=-0.013, rely=0.0, relheight=1.003, relwidth=1.008)
        self.add_teacher_frame.configure(relief='groove')
        self.add_teacher_frame.configure(borderwidth="2")
        self.add_teacher_frame.configure(relief='groove')
        self.add_teacher_frame.configure(background="#d9d9d9")
        self.add_teacher_frame.configure(width=465)

        self.Label1 = tk.Label(self.add_teacher_frame)
        self.Label1.place(relx=0.125, rely=0.163, height=23, width=65)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''教师工号  :''')

        self.Entry3 = tk.Entry(self.add_teacher_frame)
        self.Entry3.place(relx=0.35, rely=0.175, height=17, relwidth=0.36)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(textvariable=manger_support.add_teacher1)

        self.Label4 = tk.Label(self.add_teacher_frame)
        self.Label4.place(relx=0.125, rely=0.263, height=23, width=67)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''院系号码 ：''')
        self.Label4.configure(width=67)

        self.Label5 = tk.Label(self.add_teacher_frame)
        self.Label5.place(relx=0.15, rely=0.363, height=23, width=62)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''姓名     ：''')

        self.Label6 = tk.Label(self.add_teacher_frame)
        self.Label6.place(relx=0.125, rely=0.463, height=23, width=74)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''性别     ：''')
        self.Label6.configure(width=74)

        self.Label7 = tk.Label(self.add_teacher_frame)
        self.Label7.place(relx=0.15, rely=0.563, height=23, width=62)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''生日     ：''')

        self.Entry4 = tk.Entry(self.add_teacher_frame)
        self.Entry4.place(relx=0.35, rely=0.263, height=17, relwidth=0.36)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(textvariable=manger_support.add_teacher2)

        self.Label8 = tk.Label(self.add_teacher_frame)
        self.Label8.place(relx=0.15, rely=0.663, height=23, width=62)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''职称     ：''')

        self.Label9 = tk.Label(self.add_teacher_frame)
        self.Label9.place(relx=0.15, rely=0.763, height=23, width=62)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''密码     ：''')

        self.Entry5 = tk.Entry(self.add_teacher_frame)
        self.Entry5.place(relx=0.35, rely=0.375, height=17, relwidth=0.36)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(textvariable=manger_support.add_teacher3)

        self.Entry6 = tk.Entry(self.add_teacher_frame)
        self.Entry6.place(relx=0.35, rely=0.475, height=17, relwidth=0.36)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(textvariable=manger_support.add_teacher4)

        self.Entry7 = tk.Entry(self.add_teacher_frame)
        self.Entry7.place(relx=0.35, rely=0.575, height=17, relwidth=0.36)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(textvariable=manger_support.add_teacher5)

        self.Entry8 = tk.Entry(self.add_teacher_frame)
        self.Entry8.place(relx=0.35, rely=0.675, height=17, relwidth=0.36)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(textvariable=manger_support.add_teacher6)

        self.Button1 = tk.Button(self.add_teacher_frame)
        self.Button1.place(relx=0.4, rely=0.875, height=28, width=109)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=manger_support.add_teacher_button)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief='groove')
        self.Button1.configure(text='''提交''')
        self.Button1.configure(width=109)

        self.Entry9 = tk.Entry(self.add_teacher_frame)
        self.Entry9.place(relx=0.35, rely=0.775, height=17, relwidth=0.36)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(textvariable=manger_support.add_teacher7)

        self.Label10 = tk.Label(self.add_teacher_frame)
        self.Label10.place(relx=0.025, rely=0.025, height=23, width=137)
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(cursor="fleur")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(font=font12)
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''添加教师    ：''')
        self.Label10.configure(width=137)

        self.add_student_frame = tk.Frame(top)
        self.add_student_frame.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.008)
        self.add_student_frame.configure(relief='groove')
        self.add_student_frame.configure(borderwidth="2")
        self.add_student_frame.configure(relief='groove')
        self.add_student_frame.configure(background="#d9d9d9")
        self.add_student_frame.configure(highlightbackground="#d9d9d9")
        self.add_student_frame.configure(highlightcolor="black")
        self.add_student_frame.configure(width=465)

        self.Label1_3 = tk.Label(self.add_student_frame)
        self.Label1_3.place(relx=0.125, rely=0.163, height=23, width=65)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''学号     :''')

        self.Entry3_4 = tk.Entry(self.add_student_frame)
        self.Entry3_4.place(relx=0.35, rely=0.175, height=17, relwidth=0.36)
        self.Entry3_4.configure(background="white")
        self.Entry3_4.configure(disabledforeground="#a3a3a3")
        self.Entry3_4.configure(font="TkFixedFont")
        self.Entry3_4.configure(foreground="#000000")
        self.Entry3_4.configure(highlightbackground="#d9d9d9")
        self.Entry3_4.configure(highlightcolor="black")
        self.Entry3_4.configure(insertbackground="black")
        self.Entry3_4.configure(selectbackground="#c4c4c4")
        self.Entry3_4.configure(selectforeground="black")
        self.Entry3_4.configure(textvariable=manger_support.add_student1)

        self.Label4_5 = tk.Label(self.add_student_frame)
        self.Label4_5.place(relx=0.125, rely=0.263, height=23, width=67)
        self.Label4_5.configure(activebackground="#f9f9f9")
        self.Label4_5.configure(activeforeground="black")
        self.Label4_5.configure(background="#d9d9d9")
        self.Label4_5.configure(disabledforeground="#a3a3a3")
        self.Label4_5.configure(foreground="#000000")
        self.Label4_5.configure(highlightbackground="#d9d9d9")
        self.Label4_5.configure(highlightcolor="black")
        self.Label4_5.configure(text='''专业号码 ：''')

        self.Label5_6 = tk.Label(self.add_student_frame)
        self.Label5_6.place(relx=0.15, rely=0.363, height=23, width=62)
        self.Label5_6.configure(activebackground="#f9f9f9")
        self.Label5_6.configure(activeforeground="black")
        self.Label5_6.configure(background="#d9d9d9")
        self.Label5_6.configure(disabledforeground="#a3a3a3")
        self.Label5_6.configure(foreground="#000000")
        self.Label5_6.configure(highlightbackground="#d9d9d9")
        self.Label5_6.configure(highlightcolor="black")
        self.Label5_6.configure(text='''姓名     ：''')

        self.Label6_7 = tk.Label(self.add_student_frame)
        self.Label6_7.place(relx=0.125, rely=0.463, height=23, width=74)
        self.Label6_7.configure(activebackground="#f9f9f9")
        self.Label6_7.configure(activeforeground="black")
        self.Label6_7.configure(background="#d9d9d9")
        self.Label6_7.configure(disabledforeground="#a3a3a3")
        self.Label6_7.configure(foreground="#000000")
        self.Label6_7.configure(highlightbackground="#d9d9d9")
        self.Label6_7.configure(highlightcolor="black")
        self.Label6_7.configure(text='''性别     ：''')

        self.Label7_8 = tk.Label(self.add_student_frame)
        self.Label7_8.place(relx=0.15, rely=0.563, height=23, width=62)
        self.Label7_8.configure(activebackground="#f9f9f9")
        self.Label7_8.configure(activeforeground="black")
        self.Label7_8.configure(background="#d9d9d9")
        self.Label7_8.configure(disabledforeground="#a3a3a3")
        self.Label7_8.configure(foreground="#000000")
        self.Label7_8.configure(highlightbackground="#d9d9d9")
        self.Label7_8.configure(highlightcolor="black")
        self.Label7_8.configure(text='''生日     ：''')

        self.Entry4_9 = tk.Entry(self.add_student_frame)
        self.Entry4_9.place(relx=0.35, rely=0.263, height=17, relwidth=0.36)
        self.Entry4_9.configure(background="white")
        self.Entry4_9.configure(disabledforeground="#a3a3a3")
        self.Entry4_9.configure(font="TkFixedFont")
        self.Entry4_9.configure(foreground="#000000")
        self.Entry4_9.configure(highlightbackground="#d9d9d9")
        self.Entry4_9.configure(highlightcolor="black")
        self.Entry4_9.configure(insertbackground="black")
        self.Entry4_9.configure(selectbackground="#c4c4c4")
        self.Entry4_9.configure(selectforeground="black")
        self.Entry4_9.configure(textvariable=manger_support.add_student2)

        self.Label8_10 = tk.Label(self.add_student_frame)
        self.Label8_10.place(relx=0.15, rely=0.663, height=23, width=62)
        self.Label8_10.configure(activebackground="#f9f9f9")
        self.Label8_10.configure(activeforeground="black")
        self.Label8_10.configure(background="#d9d9d9")
        self.Label8_10.configure(disabledforeground="#a3a3a3")
        self.Label8_10.configure(foreground="#000000")
        self.Label8_10.configure(highlightbackground="#d9d9d9")
        self.Label8_10.configure(highlightcolor="black")
        self.Label8_10.configure(text='''密码     ：''')

        self.Entry5_12 = tk.Entry(self.add_student_frame)
        self.Entry5_12.place(relx=0.35, rely=0.375, height=17, relwidth=0.36)
        self.Entry5_12.configure(background="white")
        self.Entry5_12.configure(disabledforeground="#a3a3a3")
        self.Entry5_12.configure(font="TkFixedFont")
        self.Entry5_12.configure(foreground="#000000")
        self.Entry5_12.configure(highlightbackground="#d9d9d9")
        self.Entry5_12.configure(highlightcolor="black")
        self.Entry5_12.configure(insertbackground="black")
        self.Entry5_12.configure(selectbackground="#c4c4c4")
        self.Entry5_12.configure(selectforeground="black")
        self.Entry5_12.configure(textvariable=manger_support.add_student3)

        self.Entry6_13 = tk.Entry(self.add_student_frame)
        self.Entry6_13.place(relx=0.35, rely=0.475, height=17, relwidth=0.36)
        self.Entry6_13.configure(background="white")
        self.Entry6_13.configure(disabledforeground="#a3a3a3")
        self.Entry6_13.configure(font="TkFixedFont")
        self.Entry6_13.configure(foreground="#000000")
        self.Entry6_13.configure(highlightbackground="#d9d9d9")
        self.Entry6_13.configure(highlightcolor="black")
        self.Entry6_13.configure(insertbackground="black")
        self.Entry6_13.configure(selectbackground="#c4c4c4")
        self.Entry6_13.configure(selectforeground="black")
        self.Entry6_13.configure(textvariable=manger_support.add_student4)

        self.Entry7_14 = tk.Entry(self.add_student_frame)
        self.Entry7_14.place(relx=0.35, rely=0.575, height=17, relwidth=0.36)
        self.Entry7_14.configure(background="white")
        self.Entry7_14.configure(disabledforeground="#a3a3a3")
        self.Entry7_14.configure(font="TkFixedFont")
        self.Entry7_14.configure(foreground="#000000")
        self.Entry7_14.configure(highlightbackground="#d9d9d9")
        self.Entry7_14.configure(highlightcolor="black")
        self.Entry7_14.configure(insertbackground="black")
        self.Entry7_14.configure(selectbackground="#c4c4c4")
        self.Entry7_14.configure(selectforeground="black")
        self.Entry7_14.configure(textvariable=manger_support.add_student5)

        self.Entry8_15 = tk.Entry(self.add_student_frame)
        self.Entry8_15.place(relx=0.35, rely=0.675, height=17, relwidth=0.36)
        self.Entry8_15.configure(background="white")
        self.Entry8_15.configure(disabledforeground="#a3a3a3")
        self.Entry8_15.configure(font="TkFixedFont")
        self.Entry8_15.configure(foreground="#000000")
        self.Entry8_15.configure(highlightbackground="#d9d9d9")
        self.Entry8_15.configure(highlightcolor="black")
        self.Entry8_15.configure(insertbackground="black")
        self.Entry8_15.configure(selectbackground="#c4c4c4")
        self.Entry8_15.configure(selectforeground="black")
        self.Entry8_15.configure(textvariable=manger_support.add_student6)

        self.Button1_16 = tk.Button(self.add_student_frame)

        self.Button1_16.place(relx=0.4, rely=0.875, height=28, width=109)
        self.Button1_16.configure(activebackground="#ececec")
        self.Button1_16.configure(activeforeground="#000000")
        self.Button1_16.configure(background="#d9d9d9")
        self.Button1_16.configure(command=manger_support.add_student_button)
        self.Button1_16.configure(disabledforeground="#a3a3a3")
        self.Button1_16.configure(foreground="#000000")
        self.Button1_16.configure(highlightbackground="#d9d9d9")
        self.Button1_16.configure(highlightcolor="black")
        self.Button1_16.configure(pady="0")
        self.Button1_16.configure(relief='groove')
        self.Button1_16.configure(text='''提交''')

        self.Label10_18 = tk.Label(self.add_student_frame)
        self.Label10_18.place(relx=0.025, rely=0.025, height=23, width=137)
        self.Label10_18.configure(activebackground="#f9f9f9")
        self.Label10_18.configure(activeforeground="black")
        self.Label10_18.configure(background="#d9d9d9")
        self.Label10_18.configure(disabledforeground="#a3a3a3")
        self.Label10_18.configure(font=font12)
        self.Label10_18.configure(foreground="#000000")
        self.Label10_18.configure(highlightbackground="#d9d9d9")
        self.Label10_18.configure(highlightcolor="black")
        self.Label10_18.configure(text='''添加学生    ：''')

        self.add_course_frame = tk.Frame(top)
        self.add_course_frame.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.008)
        self.add_course_frame.configure(relief='groove')
        self.add_course_frame.configure(borderwidth="2")
        self.add_course_frame.configure(relief='groove')
        self.add_course_frame.configure(background="#d9d9d9")
        self.add_course_frame.configure(highlightbackground="#d9d9d9")
        self.add_course_frame.configure(highlightcolor="black")
        self.add_course_frame.configure(width=465)

        self.Label1_4 = tk.Label(self.add_course_frame)
        self.Label1_4.place(relx=0.125, rely=0.163, height=23, width=65)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''课程号码 :''')

        self.Entry3_5 = tk.Entry(self.add_course_frame)
        self.Entry3_5.place(relx=0.35, rely=0.175, height=17, relwidth=0.36)
        self.Entry3_5.configure(background="white")
        self.Entry3_5.configure(disabledforeground="#a3a3a3")
        self.Entry3_5.configure(font="TkFixedFont")
        self.Entry3_5.configure(foreground="#000000")
        self.Entry3_5.configure(highlightbackground="#d9d9d9")
        self.Entry3_5.configure(highlightcolor="black")
        self.Entry3_5.configure(insertbackground="black")
        self.Entry3_5.configure(selectbackground="#c4c4c4")
        self.Entry3_5.configure(selectforeground="black")
        self.Entry3_5.configure(textvariable=manger_support.add_course1)

        self.Label4_6 = tk.Label(self.add_course_frame)
        self.Label4_6.place(relx=0.138, rely=0.263, height=23, width=67)
        self.Label4_6.configure(activebackground="#f9f9f9")
        self.Label4_6.configure(activeforeground="black")
        self.Label4_6.configure(background="#d9d9d9")
        self.Label4_6.configure(disabledforeground="#a3a3a3")
        self.Label4_6.configure(foreground="#000000")
        self.Label4_6.configure(highlightbackground="#d9d9d9")
        self.Label4_6.configure(highlightcolor="black")
        self.Label4_6.configure(text='''课程名  ：''')

        self.Label5_7 = tk.Label(self.add_course_frame)
        self.Label5_7.place(relx=0.15, rely=0.363, height=23, width=62)
        self.Label5_7.configure(activebackground="#f9f9f9")
        self.Label5_7.configure(activeforeground="black")
        self.Label5_7.configure(background="#d9d9d9")
        self.Label5_7.configure(disabledforeground="#a3a3a3")
        self.Label5_7.configure(foreground="#000000")
        self.Label5_7.configure(highlightbackground="#d9d9d9")
        self.Label5_7.configure(highlightcolor="black")
        self.Label5_7.configure(text='''学分     ：''')

        self.Label6_8 = tk.Label(self.add_course_frame)
        self.Label6_8.place(relx=0.125, rely=0.463, height=23, width=74)
        self.Label6_8.configure(activebackground="#f9f9f9")
        self.Label6_8.configure(activeforeground="black")
        self.Label6_8.configure(background="#d9d9d9")
        self.Label6_8.configure(disabledforeground="#a3a3a3")
        self.Label6_8.configure(foreground="#000000")
        self.Label6_8.configure(highlightbackground="#d9d9d9")
        self.Label6_8.configure(highlightcolor="black")
        self.Label6_8.configure(text='''学时     ：''')

        self.Label7_9 = tk.Label(self.add_course_frame)
        self.Label7_9.place(relx=0.138, rely=0.563, height=23, width=62)
        self.Label7_9.configure(activebackground="#f9f9f9")
        self.Label7_9.configure(activeforeground="black")
        self.Label7_9.configure(background="#d9d9d9")
        self.Label7_9.configure(disabledforeground="#a3a3a3")
        self.Label7_9.configure(foreground="#000000")
        self.Label7_9.configure(highlightbackground="#d9d9d9")
        self.Label7_9.configure(highlightcolor="black")
        self.Label7_9.configure(text='''教师     ：''')

        self.Entry4_10 = tk.Entry(self.add_course_frame)
        self.Entry4_10.place(relx=0.35, rely=0.263, height=17, relwidth=0.36)
        self.Entry4_10.configure(background="white")
        self.Entry4_10.configure(disabledforeground="#a3a3a3")
        self.Entry4_10.configure(font="TkFixedFont")
        self.Entry4_10.configure(foreground="#000000")
        self.Entry4_10.configure(highlightbackground="#d9d9d9")
        self.Entry4_10.configure(highlightcolor="black")
        self.Entry4_10.configure(insertbackground="black")
        self.Entry4_10.configure(selectbackground="#c4c4c4")
        self.Entry4_10.configure(selectforeground="black")
        self.Entry4_10.configure(textvariable=manger_support.add_course2)

        self.Entry5_13 = tk.Entry(self.add_course_frame)
        self.Entry5_13.place(relx=0.35, rely=0.375, height=17, relwidth=0.36)
        self.Entry5_13.configure(background="white")
        self.Entry5_13.configure(disabledforeground="#a3a3a3")
        self.Entry5_13.configure(font="TkFixedFont")
        self.Entry5_13.configure(foreground="#000000")
        self.Entry5_13.configure(highlightbackground="#d9d9d9")
        self.Entry5_13.configure(highlightcolor="black")
        self.Entry5_13.configure(insertbackground="black")
        self.Entry5_13.configure(selectbackground="#c4c4c4")
        self.Entry5_13.configure(selectforeground="black")
        self.Entry5_13.configure(textvariable=manger_support.add_course3)

        self.Entry6_14 = tk.Entry(self.add_course_frame)
        self.Entry6_14.place(relx=0.35, rely=0.475, height=17, relwidth=0.36)
        self.Entry6_14.configure(background="white")
        self.Entry6_14.configure(disabledforeground="#a3a3a3")
        self.Entry6_14.configure(font="TkFixedFont")
        self.Entry6_14.configure(foreground="#000000")
        self.Entry6_14.configure(highlightbackground="#d9d9d9")
        self.Entry6_14.configure(highlightcolor="black")
        self.Entry6_14.configure(insertbackground="black")
        self.Entry6_14.configure(selectbackground="#c4c4c4")
        self.Entry6_14.configure(selectforeground="black")
        self.Entry6_14.configure(textvariable=manger_support.add_course4)

        self.Entry7_15 = tk.Entry(self.add_course_frame)
        self.Entry7_15.place(relx=0.35, rely=0.575, height=17, relwidth=0.36)
        self.Entry7_15.configure(background="white")
        self.Entry7_15.configure(disabledforeground="#a3a3a3")
        self.Entry7_15.configure(font="TkFixedFont")
        self.Entry7_15.configure(foreground="#000000")
        self.Entry7_15.configure(highlightbackground="#d9d9d9")
        self.Entry7_15.configure(highlightcolor="black")
        self.Entry7_15.configure(insertbackground="black")
        self.Entry7_15.configure(selectbackground="#c4c4c4")
        self.Entry7_15.configure(selectforeground="black")
        self.Entry7_15.configure(textvariable=manger_support.add_course5)

        self.Button1_17 = tk.Button(self.add_course_frame)
        self.Button1_17.place(relx=0.4, rely=0.875, height=28, width=109)
        self.Button1_17.configure(activebackground="#ececec")
        self.Button1_17.configure(activeforeground="#000000")
        self.Button1_17.configure(background="#d9d9d9")
        self.Button1_17.configure(command=manger_support.add_course_button)
        self.Button1_17.configure(disabledforeground="#a3a3a3")
        self.Button1_17.configure(foreground="#000000")
        self.Button1_17.configure(highlightbackground="#d9d9d9")
        self.Button1_17.configure(highlightcolor="black")
        self.Button1_17.configure(pady="0")
        self.Button1_17.configure(relief='groove')
        self.Button1_17.configure(text='''提交''')

        self.Label10_19 = tk.Label(self.add_course_frame)
        self.Label10_19.place(relx=0.025, rely=0.025, height=23, width=137)
        self.Label10_19.configure(activebackground="#f9f9f9")
        self.Label10_19.configure(activeforeground="black")
        self.Label10_19.configure(background="#d9d9d9")
        self.Label10_19.configure(disabledforeground="#a3a3a3")
        self.Label10_19.configure(font=font12)
        self.Label10_19.configure(foreground="#000000")
        self.Label10_19.configure(highlightbackground="#d9d9d9")
        self.Label10_19.configure(highlightcolor="black")
        self.Label10_19.configure(text='''添加课程    ：''')

        self.control_frame = tk.Frame(top)
        self.control_frame.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.008)
        self.control_frame.configure(relief='groove')
        self.control_frame.configure(borderwidth="2")
        self.control_frame.configure(relief='groove')
        self.control_frame.configure(background="#d9d9d9")
        self.control_frame.configure(width=125)

        self.Radiobutton1 = tk.Radiobutton(self.control_frame)
        self.Radiobutton1.place(relx=0.475, rely=0.275, relheight=0.068, relwidth=0.1)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(command=manger_support.is_time_select_course_func)
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''是''')
        self.Radiobutton1.configure(value="1")
        self.Radiobutton1.configure(variable=manger_support.is_time_select_course_var)

        self.Radiobutton2 = tk.Radiobutton(self.control_frame)
        self.Radiobutton2.place(relx=0.65, rely=0.275, relheight=0.068, relwidth=0.1)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(command=manger_support.is_time_select_course_func)
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''否''')
        self.Radiobutton2.configure(value="0")
        self.Radiobutton2.configure(variable=manger_support.is_time_select_course_var)

        self.Label11 = tk.Label(self.control_frame)
        self.Label11.place(relx=0.075, rely=0.275, height=23, width=150)
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''是否是选课时间     ：''')
        self.Label11.configure(width=150)

        self.Label11_20 = tk.Label(self.control_frame)
        self.Label11_20.place(relx=0.075, rely=0.425, height=23, width=146)
        self.Label11_20.configure(activebackground="#f9f9f9")
        self.Label11_20.configure(activeforeground="black")
        self.Label11_20.configure(background="#d9d9d9")
        self.Label11_20.configure(disabledforeground="#a3a3a3")
        self.Label11_20.configure(foreground="#000000")
        self.Label11_20.configure(highlightbackground="#d9d9d9")
        self.Label11_20.configure(highlightcolor="black")
        self.Label11_20.configure(text='''是否是成绩录入时间 ：''')
        self.Label11_20.configure(width=146)

        self.Radiobutton1_21 = tk.Radiobutton(self.control_frame)
        self.Radiobutton1_21.place(relx=0.475, rely=0.425, relheight=0.068, relwidth=0.1)
        self.Radiobutton1_21.configure(activebackground="#ececec")
        self.Radiobutton1_21.configure(activeforeground="#000000")
        self.Radiobutton1_21.configure(background="#d9d9d9")
        self.Radiobutton1_21.configure(command=manger_support.is_time_grade_input_func)
        self.Radiobutton1_21.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_21.configure(foreground="#000000")
        self.Radiobutton1_21.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_21.configure(highlightcolor="black")
        self.Radiobutton1_21.configure(justify='left')
        self.Radiobutton1_21.configure(text='''是''')
        self.Radiobutton1_21.configure(value="1")
        self.Radiobutton1_21.configure(variable=manger_support.is_time_grade_input_var)

        self.Radiobutton2_22 = tk.Radiobutton(self.control_frame)
        self.Radiobutton2_22.place(relx=0.65, rely=0.425, relheight=0.068, relwidth=0.1)
        self.Radiobutton2_22.configure(activebackground="#ececec")
        self.Radiobutton2_22.configure(activeforeground="#000000")
        self.Radiobutton2_22.configure(background="#d9d9d9")
        self.Radiobutton2_22.configure(command=manger_support.is_time_grade_input_func)
        self.Radiobutton2_22.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_22.configure(foreground="#000000")
        self.Radiobutton2_22.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_22.configure(highlightcolor="black")
        self.Radiobutton2_22.configure(justify='left')
        self.Radiobutton2_22.configure(text='''否''')
        self.Radiobutton2_22.configure(value="0")
        self.Radiobutton2_22.configure(variable=manger_support.is_time_grade_input_var)

        self.Label12 = tk.Label(self.control_frame)
        self.Label12.place(relx=0.025, rely=0.025, height=28, width=96)
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(font=font10)
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''控制字段  ：''')

        self.change_password_frame = tk.Frame(top)
        self.change_password_frame.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.008)
        self.change_password_frame.configure(relief='groove')
        self.change_password_frame.configure(borderwidth="2")
        self.change_password_frame.configure(relief='groove')
        self.change_password_frame.configure(background="#d9d9d9")
        self.change_password_frame.configure(width=125)

        self.Label13 = tk.Label(self.change_password_frame)
        self.Label13.place(relx=0.025, rely=0.025, height=28, width=96)
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(font=font10)
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''修改密码  ：''')

        self.Label14 = tk.Label(self.change_password_frame)
        self.Label14.place(relx=0.125, rely=0.2, height=23, width=79)
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(text='''user ：''')
        self.Label14.configure(width=77)

        self.Label15 = tk.Label(self.change_password_frame)
        self.Label15.place(relx=0.35, rely=0.2, height=23, width=90)
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(text='''用户''')
        self.Label15.configure(textvariable=manger_support.user_var)
        self.Label15.configure(width=90)

        self.Label16 = tk.Label(self.change_password_frame)
        self.Label16.place(relx=0.125, rely=0.316, height=23, width=79)
        self.Label16.configure(background="#d9d9d9")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(text='''原密码：''')

        self.Entry10 = tk.Entry(self.change_password_frame)
        self.Entry10.place(relx=0.35, rely=0.325, height=17, relwidth=0.36)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(show="*")
        self.Entry10.configure(textvariable=manger_support.password)

        self.Label16_23 = tk.Label(self.change_password_frame)
        self.Label16_23.place(relx=0.125, rely=0.440, height=23, width=79)
        self.Label16_23.configure(activebackground="#f9f9f9")
        self.Label16_23.configure(activeforeground="black")
        self.Label16_23.configure(background="#d9d9d9")
        self.Label16_23.configure(disabledforeground="#a3a3a3")
        self.Label16_23.configure(foreground="#000000")
        self.Label16_23.configure(highlightbackground="#d9d9d9")
        self.Label16_23.configure(highlightcolor="black")
        self.Label16_23.configure(text='''新密码：''')
        self.Label16_23.configure(width=119)

        self.Entry11 = tk.Entry(self.change_password_frame)
        self.Entry11.place(relx=0.35, rely=0.45, height=17, relwidth=0.36)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(show="*")
        self.Entry11.configure(textvariable=manger_support.change_password_var)

        # 修改密码页面message
        self.Message2 = tk.Message(self.change_password_frame)
        self.Message2.place(relx=0.30, rely=0.035, relheight=0.050, relwidth=0.443)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(textvariable=manger_support.message2)
        self.Message2.configure(width=177)

        # 课程页面message
        self.Message3 = tk.Message(self.add_course_frame)
        self.Message3.place(relx=0.30, rely=0.035, relheight=0.050, relwidth=0.443)
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(textvariable=manger_support.message3)
        self.Message3.configure(width=177)

        # 学生页面message
        self.Message4 = tk.Message(self.add_student_frame)
        self.Message4.place(relx=0.30, rely=0.035, relheight=0.050, relwidth=0.443)
        self.Message4.configure(background="#d9d9d9")
        self.Message4.configure(foreground="#000000")
        self.Message4.configure(highlightbackground="#d9d9d9")
        self.Message4.configure(highlightcolor="black")
        self.Message4.configure(textvariable=manger_support.message4)
        self.Message4.configure(width=177)

        # 教师页面message
        self.Message5 = tk.Message(self.add_teacher_frame)
        self.Message5.place(relx=0.30, rely=0.035, relheight=0.050, relwidth=0.443)
        self.Message5.configure(background="#d9d9d9")
        self.Message5.configure(foreground="#000000")
        self.Message5.configure(highlightbackground="#d9d9d9")
        self.Message5.configure(highlightcolor="black")
        self.Message5.configure(textvariable=manger_support.message5)
        self.Message5.configure(width=177)

        self.Button2 = tk.Button(self.change_password_frame)
        self.Button2.place(relx=0.4, rely=0.6, height=28, width=109)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=manger_support.change_password_button)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief='groove')
        self.Button2.configure(text='''提交''')
        self.Button2.configure(width=109)

        self.myself_frame = tk.Frame(top)
        self.myself_frame.place(relx=0.0, rely=0.0, relheight=1.003, relwidth=1.008)
        self.myself_frame.configure(relief='groove')
        self.myself_frame.configure(borderwidth="2")
        self.myself_frame.configure(relief='groove')
        self.myself_frame.configure(background="#d9d9d9")
        self.myself_frame.configure(highlightbackground="#d9d9d9")
        self.myself_frame.configure(highlightcolor="black")
        self.myself_frame.configure(width=400)

        self.Label1_5 = tk.Label(self.myself_frame)
        self.Label1_5.place(relx=0.1, rely=0.163, height=23, width=75)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''管理员工号 :''')
        self.Label1_5.configure(width=75)

        self.Label4_7 = tk.Label(self.myself_frame)
        self.Label4_7.place(relx=0.138, rely=0.263, height=23, width=67)
        self.Label4_7.configure(activebackground="#f9f9f9")
        self.Label4_7.configure(activeforeground="black")
        self.Label4_7.configure(background="#d9d9d9")
        self.Label4_7.configure(disabledforeground="#a3a3a3")
        self.Label4_7.configure(foreground="#000000")
        self.Label4_7.configure(highlightbackground="#d9d9d9")
        self.Label4_7.configure(highlightcolor="black")
        self.Label4_7.configure(text='''姓名     ：''')

        self.Label5_8 = tk.Label(self.myself_frame)
        self.Label5_8.place(relx=0.15, rely=0.363, height=23, width=62)
        self.Label5_8.configure(activebackground="#f9f9f9")
        self.Label5_8.configure(activeforeground="black")
        self.Label5_8.configure(background="#d9d9d9")
        self.Label5_8.configure(disabledforeground="#a3a3a3")
        self.Label5_8.configure(foreground="#000000")
        self.Label5_8.configure(highlightbackground="#d9d9d9")
        self.Label5_8.configure(highlightcolor="black")
        self.Label5_8.configure(text='''性别     ：''')

        self.Label6_9 = tk.Label(self.myself_frame)
        self.Label6_9.place(relx=0.125, rely=0.463, height=23, width=74)
        self.Label6_9.configure(activebackground="#f9f9f9")
        self.Label6_9.configure(activeforeground="black")
        self.Label6_9.configure(background="#d9d9d9")
        self.Label6_9.configure(disabledforeground="#a3a3a3")
        self.Label6_9.configure(foreground="#000000")
        self.Label6_9.configure(highlightbackground="#d9d9d9")
        self.Label6_9.configure(highlightcolor="black")
        self.Label6_9.configure(text='''生日     ：''')

        self.Label10_16 = tk.Label(self.myself_frame)
        self.Label10_16.place(relx=0.025, rely=0.025, height=23, width=137)
        self.Label10_16.configure(activebackground="#f9f9f9")
        self.Label10_16.configure(activeforeground="black")
        self.Label10_16.configure(background="#d9d9d9")
        self.Label10_16.configure(disabledforeground="#a3a3a3")
        self.Label10_16.configure(font=font12)
        self.Label10_16.configure(foreground="#000000")
        self.Label10_16.configure(highlightbackground="#d9d9d9")
        self.Label10_16.configure(highlightcolor="black")
        self.Label10_16.configure(text='''个人资料    ：''')

        self.Label17 = tk.Label(self.myself_frame)
        self.Label17.place(relx=0.4, rely=0.175, height=23, width=6)
        self.Label17.configure(background="#d9d9d9")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#000000")

        self.Label18_20 = tk.Label(self.myself_frame)
        self.Label18_20.place(relx=0.4, rely=0.275, height=23, width=117)
        self.Label18_20.configure(activebackground="#f9f9f9")
        self.Label18_20.configure(activeforeground="black")
        self.Label18_20.configure(background="#d9d9d9")
        self.Label18_20.configure(disabledforeground="#a3a3a3")
        self.Label18_20.configure(foreground="#000000")
        self.Label18_20.configure(highlightbackground="#d9d9d9")
        self.Label18_20.configure(highlightcolor="black")
        self.Label18_20.configure(text='''工号''')
        self.Label18_20.configure(textvariable=manger_support.username)

        self.Label18_21 = tk.Label(self.myself_frame)
        self.Label18_21.place(relx=0.4, rely=0.463, height=23, width=117)
        self.Label18_21.configure(activebackground="#f9f9f9")
        self.Label18_21.configure(activeforeground="black")
        self.Label18_21.configure(background="#d9d9d9")
        self.Label18_21.configure(disabledforeground="#a3a3a3")
        self.Label18_21.configure(foreground="#000000")
        self.Label18_21.configure(highlightbackground="#d9d9d9")
        self.Label18_21.configure(highlightcolor="black")
        self.Label18_21.configure(text='''工号''')
        self.Label18_21.configure(textvariable=manger_support.user_birthday)

        self.Label18_23 = tk.Label(self.myself_frame)
        self.Label18_23.place(relx=0.4, rely=0.363, height=23, width=117)
        self.Label18_23.configure(activebackground="#f9f9f9")
        self.Label18_23.configure(activeforeground="black")
        self.Label18_23.configure(background="#d9d9d9")
        self.Label18_23.configure(disabledforeground="#a3a3a3")
        self.Label18_23.configure(foreground="#000000")
        self.Label18_23.configure(highlightbackground="#d9d9d9")
        self.Label18_23.configure(highlightcolor="black")
        self.Label18_23.configure(text='''工号''')
        self.Label18_23.configure(textvariable=manger_support.user_sex)

        self.Label18_21 = tk.Label(self.myself_frame)
        self.Label18_21.place(relx=0.375, rely=0.163, height=23, width=137)
        self.Label18_21.configure(activebackground="#f9f9f9")
        self.Label18_21.configure(activeforeground="black")
        self.Label18_21.configure(background="#d9d9d9")
        self.Label18_21.configure(disabledforeground="#a3a3a3")
        self.Label18_21.configure(foreground="#000000")
        self.Label18_21.configure(highlightbackground="#d9d9d9")
        self.Label18_21.configure(highlightcolor="black")
        self.Label18_21.configure(textvariable=manger_support.user)

        self.firstframe.tkraise()

        self.menubar.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.firstframe.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="首页")
        self.sub_menu = tk.Menu(top, tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                                 activebackground="#ececec",
                                 activeforeground="#000000",
                                 background="#d9d9d9",
                                 compound="left",
                                 font="TkMenuFont",
                                 foreground="#000000",
                                 label="添加成员")
        self.sub_menu.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.add_teacher_frame.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="添加教师")
        self.sub_menu.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.add_student_frame.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="添加学生")
        self.menubar.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.add_course_frame.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="添加可选课程")
        self.menubar.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.control_frame.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="控制")
        self.sub_menu1 = tk.Menu(top, tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                                 activebackground="#ececec",
                                 activeforeground="#000000",
                                 background="#d9d9d9",
                                 compound="left",
                                 font="TkMenuFont",
                                 foreground="#000000",
                                 label="User")
        self.sub_menu1.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.change_password_frame.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="修改密码")
        self.sub_menu1.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.myself_frame.tkraise,
            compound="left",
            font="TkMenuFont",
            foreground="#000000",
            label="个人资料")


if __name__ == '__main__':
    vp_start_gui('001')
