#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 26, 2018 03:56:22 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

from system import start_support


def vp_start_gui():
    # '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    start_support.set_tk_var()
    top = Toplevel1(root)
    start_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    # '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    start_support.set_tk_var()
    top = Toplevel1(w)
    start_support.init(w, top, *args, **kwargs)
    return w, top


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        # '''This class configures and populates the toplevel window.
        #    top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font10 = "-family 新宋体 -size 10 -weight normal -slant roman " \
                 "-underline 0 -overstrike 0"
        font9 = "-family {Microsoft YaHei UI} -size 24 -weight bold " \
                "-slant roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=[('selected', _compcolor), ('active', _ana2color)])

        # top.geometry("573x472")
        top.geometry("399x399+601+123")
        top.title("学生信息管理系统登陆")
        top.configure(background="#d9d9d9")

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.244, rely=0.169, height=23, width=58)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''用户名 ：''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.244, rely=0.275, height=23, width=58)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''密码   ：''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.2896, rely=0.614, height=28, width=35)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=start_support.put_in)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''提交''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.611, rely=0.614, height=28, width=35)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''刷新''')

        self.tLa56 = ttk.Label(top)
        self.tLa56.place(relx=0.192, rely=0.042, height=41, width=329)
        self.tLa56.configure(background="#d9d9d9")
        self.tLa56.configure(foreground="#000000")
        self.tLa56.configure(font=font9)
        self.tLa56.configure(relief='flat')
        self.tLa56.configure(text='''学生信息管理系统''')
        self.tLa56.configure(state='active')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.384, rely=0.169, height=17, relwidth=0.251)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        # self.Entry1.configure(textvariable=known_support.user1)
        self.Entry1.configure(textvariable=start_support.user1)
        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.384, rely=0.275, height=17, relwidth=0.251)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#d9d9d9")
        self.Entry2.configure(font=font10)
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(show="*")
        self.Entry2.configure(textvariable=start_support.password1)

        self.Radiobutton1 = tk.Radiobutton(top)
        self.Radiobutton1.place(relx=0.165, rely=0.466, relheight=0.057, relwidth=0.15)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(command=start_support.select_table)
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''学生''')
        self.Radiobutton1.configure(value="tb_student")
        self.Radiobutton1.configure(variable=start_support.var)

        self.Radiobutton2 = tk.Radiobutton(top)
        self.Radiobutton2.place(relx=0.414, rely=0.466, relheight=0.057, relwidth=0.15)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#d9d9d9")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(command=start_support.select_table)
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''教师''')
        self.Radiobutton2.configure(value="tb_teacher")
        self.Radiobutton2.configure(variable=start_support.var)

        self.Radiobutton3 = tk.Radiobutton(top)
        self.Radiobutton3.place(relx=0.663, rely=0.466, relheight=0.057, relwidth=0.15)
        self.Radiobutton3.configure(activebackground="#ececec")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(command=start_support.select_table)
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify='left')
        self.Radiobutton3.configure(overrelief="flat")
        self.Radiobutton3.configure(selectcolor="#ffffff")
        self.Radiobutton3.configure(text='''管理员''')
        self.Radiobutton3.configure(value="tb_manager")
        self.Radiobutton3.configure(variable=start_support.var)

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.332, rely=0.742, height=17, relwidth=0.321)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(textvariable=start_support.return_value)
        self.Entry3.configure(width=184)


if __name__ == '__main__':
    vp_start_gui()
